<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="63" failures="13" name="TestSuite" time="0.033" errors="0" skipped="0">
  <properties>
    <property name="idea.version" value="2017.2.5"/>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="C:\Program Files\Java\jdk1.8.0_151\jre\bin"/>
    <property name="java.vm.version" value="25.151-b12"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="maven.multiModuleProjectDirectory" value="C:\Users\Oksana_Starazhok\IdeaProjects\UnitTestTask\UnitTestTask"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=";"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.script" value=""/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="C:\Users\Oksana_Starazhok\IdeaProjects\UnitTestTask\UnitTestTask"/>
    <property name="java.runtime.version" value="1.8.0_151-b12"/>
    <property name="java.awt.graphicsenv" value="sun.awt.Win32GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="C:\Program Files\Java\jdk1.8.0_151\jre\lib\endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="C:\Users\OKSANA~1\AppData\Local\Temp\"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="user.variant" value=""/>
    <property name="os.name" value="Windows 10"/>
    <property name="classworlds.conf" value="C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\plugins\maven\lib\maven3\bin\m2.conf"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\Program Files\Java\jdk1.8.0_151\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files (x86)\CheckPoint\Endpoint Security\Endpoint Common\bin;C:\Program Files\Java\jdk1.8.0_151\bin;C:\Users\Oksana_Starazhok\AppData\Local\Microsoft\WindowsApps;;."/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="10.0"/>
    <property name="user.home" value="C:\Users\Oksana_Starazhok"/>
    <property name="user.timezone" value="Europe/Minsk"/>
    <property name="java.awt.printerjob" value="sun.awt.windows.WPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="user.name" value="Oksana_Starazhok"/>
    <property name="java.class.path" value="C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\plugins\maven\lib\maven3\boot\plexus-classworlds-2.5.2.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\lib\idea_rt.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="C:\Program Files\Java\jdk1.8.0_151\jre"/>
    <property name="sun.java.command" value="org.codehaus.classworlds.Launcher -Didea.version=2017.2.5 test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.windows.WToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_151"/>
    <property name="java.ext.dirs" value="C:\Program Files\Java\jdk1.8.0_151\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext"/>
    <property name="sun.boot.class.path" value="C:\Program Files\Java\jdk1.8.0_151\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\sunrsasign.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_151\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_151\jre\classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.2.5\plugins\maven\lib\maven3"/>
    <property name="file.separator" value="\"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.desktop" value="windows"/>
    <property name="sun.cpu.isalist" value="amd64"/>
  </properties>
  <testcase classname="TestDiv" name="firstDivideSecond" time="0.002"/>
  <testcase classname="TestDiv" name="firstDivideSecond" time="0"/>
  <testcase classname="TestDiv" name="firstDivideSecond" time="0"/>
  <testcase classname="TestMult" name="firstTimesSecond" time="0"/>
  <testcase classname="TestMult" name="firstTimesSecond" time="0"/>
  <testcase classname="TestMult" name="firstTimesSecond" time="0"/>
  <testcase classname="TestMult" name="firstTimesSecond" time="0"/>
  <testcase classname="TestSub" name="firstMinusSecondLong" time="0"/>
  <testcase classname="TestSub" name="firstMinusSecondLong" time="0"/>
  <testcase classname="TestSub" name="firstMinusSecondLong" time="0"/>
  <testcase classname="TestSub" name="firstMinusSecondLong" time="0"/>
  <testcase classname="TestSum" name="firstPlusSecond" time="0"/>
  <testcase classname="TestSum" name="firstPlusSecond" time="0"/>
  <testcase classname="TestSum" name="firstPlusSecond" time="0"/>
  <testcase classname="TestSum" name="firstPlusSecond" time="0"/>
  <testcase classname="TestTg" name="tgOfNumber" time="0.016">
    <failure message="expected:&lt;0.0&gt; but was:&lt;NaN&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;0.0&gt; but was:&lt;NaN&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at TestTg.tgOfNumber(TestTg.java:10)
</failure>
    <system-out>Current time:  Fri Apr 20 10:18:20 MSK 2018
Return initial configuration back
Create new instance of Calculator
</system-out>
  </testcase>
  <testcase classname="TestTg" name="tgOfNumber" time="0">
    <failure message="expected:&lt;0.9981778976111987&gt; but was:&lt;1.0&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;0.9981778976111987&gt; but was:&lt;1.0&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at TestTg.tgOfNumber(TestTg.java:10)
</failure>
  </testcase>
  <testcase classname="TestTg" name="tgOfNumber" time="0"/>
  <testcase classname="TestDivNegativeDouble" name="doubleDivisionOnZero" time="0">
    <failure message="
Method TestDivNegativeDouble.doubleDivisionOnZero() should have thrown an exception of class java.lang.NumberFormatException" type="org.testng.TestException">org.testng.TestException: 
Method TestDivNegativeDouble.doubleDivisionOnZero() should have thrown an exception of class java.lang.NumberFormatException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1443)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:722)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</failure>
    <system-out>Current time:  Fri Apr 20 10:18:20 MSK 2018
Return initial configuration back
Create new instance of Calculator
</system-out>
  </testcase>
  <testcase classname="TestIsPositive" name="checkNumber" time="0"/>
  <testcase classname="TestIsPositive" name="checkNumber" time="0"/>
  <testcase classname="TestIsPositive" name="checkNumber" time="0"/>
  <testcase classname="TestIsPositive" name="checkNumber" time="0"/>
  <testcase classname="TestSin" name="sinOfNumber" time="0"/>
  <testcase classname="TestSin" name="sinOfNumber" time="0"/>
  <testcase classname="TestSin" name="sinOfNumber" time="0"/>
  <testcase classname="TestSin" name="sinOfNumber" time="0"/>
  <testcase classname="TestSumDouble" name="firstPlusSecond" time="0"/>
  <testcase classname="TestSumDouble" name="firstPlusSecond" time="0"/>
  <testcase classname="TestSumDouble" name="firstPlusSecond" time="0"/>
  <testcase classname="TestSumDouble" name="firstPlusSecond" time="0"/>
  <testcase classname="TestSumDouble" name="firstPlusSecond" time="0"/>
  <testcase classname="TestSqrt" name="sqrtOfNumber" time="0"/>
  <testcase classname="TestSqrt" name="sqrtOfNumber" time="0"/>
  <testcase classname="TestSqrt" name="sqrtOfNumber" time="0"/>
  <testcase classname="TestCos" name="cosOfNumber" time="0">
    <failure message="expected:&lt;1.0&gt; but was:&lt;0.0&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;1.0&gt; but was:&lt;0.0&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at TestCos.cosOfNumber(TestCos.java:11)
</failure>
    <system-out>Current time:  Fri Apr 20 10:18:20 MSK 2018
Return initial configuration back
Create new instance of Calculator
</system-out>
  </testcase>
  <testcase classname="TestCos" name="cosOfNumber" time="0">
    <failure message="expected:&lt;0.0&gt; but was:&lt;1.0&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;0.0&gt; but was:&lt;1.0&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at TestCos.cosOfNumber(TestCos.java:11)
</failure>
  </testcase>
  <testcase classname="TestCos" name="cosOfNumber" time="0">
    <failure message="expected:&lt;1.0&gt; but was:&lt;-2.4492935982947064E-16&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;1.0&gt; but was:&lt;-2.4492935982947064E-16&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at TestCos.cosOfNumber(TestCos.java:11)
</failure>
  </testcase>
  <testcase classname="TestCos" name="cosOfNumber" time="0">
    <failure message="expected:&lt;-1.0&gt; but was:&lt;1.2246467991473532E-16&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;-1.0&gt; but was:&lt;1.2246467991473532E-16&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at TestCos.cosOfNumber(TestCos.java:11)
</failure>
  </testcase>
  <testcase classname="TestIsNegative" name="checkNumber" time="0">
    <failure message="expected:&lt;false&gt; but was:&lt;true&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;false&gt; but was:&lt;true&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:281)
	at org.testng.Assert.assertEquals(Assert.java:291)
	at TestIsNegative.checkNumber(TestIsNegative.java:28)
</failure>
    <system-out>Current time:  Fri Apr 20 10:18:20 MSK 2018
Return initial configuration back
Create new instance of Calculator
</system-out>
  </testcase>
  <testcase classname="TestIsNegative" name="checkNumber" time="0">
    <failure message="expected:&lt;true&gt; but was:&lt;false&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;true&gt; but was:&lt;false&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:281)
	at org.testng.Assert.assertEquals(Assert.java:291)
	at TestIsNegative.checkNumber(TestIsNegative.java:28)
</failure>
    <system-out>Current time:  Fri Apr 20 10:18:20 MSK 2018
Return initial configuration back
Create new instance of Calculator
</system-out>
  </testcase>
  <testcase classname="TestIsNegative" name="checkNumber" time="0"/>
  <testcase classname="TestIsNegative" name="checkNumber" time="0">
    <failure message="expected:&lt;true&gt; but was:&lt;false&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;true&gt; but was:&lt;false&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:281)
	at org.testng.Assert.assertEquals(Assert.java:291)
	at TestIsNegative.checkNumber(TestIsNegative.java:28)
</failure>
    <system-out>Current time:  Fri Apr 20 10:18:20 MSK 2018
Return initial configuration back
Create new instance of Calculator
</system-out>
  </testcase>
  <testcase classname="TestMultDouble" name="firstTimesSecond" time="0"/>
  <testcase classname="TestMultDouble" name="firstTimesSecond" time="0.015"/>
  <testcase classname="TestMultDouble" name="firstTimesSecond" time="0">
    <failure message="expected:&lt;0.25&gt; but was:&lt;0.0&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;0.25&gt; but was:&lt;0.0&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at TestMultDouble.firstTimesSecond(TestMultDouble.java:31)
</failure>
    <system-out>Current time:  Fri Apr 20 10:18:20 MSK 2018
Return initial configuration back
Create new instance of Calculator
</system-out>
  </testcase>
  <testcase classname="TestMultDouble" name="firstTimesSecond" time="0"/>
  <testcase classname="TestDivNegative" name="devisionOnZero" time="0"/>
  <testcase classname="TestCtg" name="ctgOfNumber" time="0"/>
  <testcase classname="TestCtg" name="ctgOfNumber" time="0"/>
  <testcase classname="TestCtg" name="ctgOfNumber" time="0"/>
  <testcase classname="TestPowNegative" name="powDivisionOnZero" time="0">
    <failure message="
Method TestPowNegative.powDivisionOnZero() should have thrown an exception of class java.lang.ArithmeticException" type="org.testng.TestException">org.testng.TestException: 
Method TestPowNegative.powDivisionOnZero() should have thrown an exception of class java.lang.ArithmeticException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1443)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:722)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</failure>
    <system-out>Current time:  Fri Apr 20 10:18:20 MSK 2018
Return initial configuration back
Create new instance of Calculator
</system-out>
  </testcase>
  <testcase classname="TestSubDouble" name="firstMinusSecondDP" time="0"/>
  <testcase classname="TestSubDouble" name="firstMinusSecondDP" time="0">
    <failure message="expected:&lt;-0.7&gt; but was:&lt;-0.7000000000000002&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;-0.7&gt; but was:&lt;-0.7000000000000002&gt;
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:160)
	at TestSubDouble.firstMinusSecondDP(TestSubDouble.java:30)
</failure>
    <system-out>Current time:  Fri Apr 20 10:18:20 MSK 2018
Return initial configuration back
Create new instance of Calculator
</system-out>
  </testcase>
  <testcase classname="TestSubDouble" name="firstMinusSecondDP" time="0"/>
  <testcase classname="TestPow" name="testPow" time="0"/>
  <testcase classname="TestPow" name="testPow" time="0"/>
  <testcase classname="TestPow" name="testPow" time="0"/>
  <testcase classname="TestPow" name="testPow" time="0"/>
  <testcase classname="TestPow" name="testPow" time="0"/>
  <testcase classname="TestPow" name="testPow" time="0"/>
  <testcase classname="TestDivDouble" name="firstDivideSecond" time="0"/>
  <testcase classname="TestDivDouble" name="firstDivideSecond" time="0"/>
</testsuite>